Search.appendIndex(
    [
                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog",
            "name": "Dog",
            "summary": "A\u0020cute\u0020dog\u0021",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#method___construct"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "name\u0020of\u0020the\u0020animal,\u0020like\u0020\u0027Fluffy\u0027",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#method_getName"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003AgetAge\u0028\u0029",
            "name": "getAge",
            "summary": "age\u0020of\u0020dog\u0020in\u0020years",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#method_getAge"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "type\u0020of\u0020the\u0020animal,\u0020like\u0020cat,\u0020alligator,\u0020tiger",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#method_getType"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003AgetSound\u0028\u0029",
            "name": "getSound",
            "summary": "the\u0020sound\u0020that\u0020the\u0020animal\u0020makes",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#method_getSound"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#property_name"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\Dog\u003A\u003A\u0024age",
            "name": "age",
            "summary": "",
            "url": "classes/Neoncitylights-ExampleLibrary-Dog.html#property_age"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\IAnimal",
            "name": "IAnimal",
            "summary": "An\u0020interface\u0020for\u0020the\u0020behaviors\u0020and\u0020properties\u0020of\u0020animals.",
            "url": "classes/Neoncitylights-ExampleLibrary-IAnimal.html"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\IAnimal\u003A\u003AgetName\u0028\u0029",
            "name": "getName",
            "summary": "name\u0020of\u0020the\u0020animal,\u0020like\u0020\u0027Fluffy\u0027",
            "url": "classes/Neoncitylights-ExampleLibrary-IAnimal.html#method_getName"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\IAnimal\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "type\u0020of\u0020the\u0020animal,\u0020like\u0020cat,\u0020alligator,\u0020tiger",
            "url": "classes/Neoncitylights-ExampleLibrary-IAnimal.html#method_getType"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\IAnimal\u003A\u003AgetSound\u0028\u0029",
            "name": "getSound",
            "summary": "the\u0020sound\u0020that\u0020the\u0020animal\u0020makes",
            "url": "classes/Neoncitylights-ExampleLibrary-IAnimal.html#method_getSound"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary\\IAnimal\u003A\u003AgetAge\u0028\u0029",
            "name": "getAge",
            "summary": "age\u0020of\u0020dog\u0020in\u0020years",
            "url": "classes/Neoncitylights-ExampleLibrary-IAnimal.html#method_getAge"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Neoncitylights\\ExampleLibrary",
            "name": "ExampleLibrary",
            "summary": "",
            "url": "namespaces/neoncitylights-examplelibrary.html"
        },                {
            "fqsen": "\\Neoncitylights",
            "name": "Neoncitylights",
            "summary": "",
            "url": "namespaces/neoncitylights.html"
        }            ]
);
